if(EXISTS "/home/nicol-briatico/Scrivania/Progetto_PCS/Projects/Release/raffinamento_test[1]_tests.cmake")
  include("/home/nicol-briatico/Scrivania/Progetto_PCS/Projects/Release/raffinamento_test[1]_tests.cmake")
else()
  add_test(raffinamento_test_NOT_BUILT raffinamento_test_NOT_BUILT)
endif()
